---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment
  template:
    metadata:
      labels:
        name: payment
      {{- if .Values.istio.enabled }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      {{- end }}
    spec:
      containers:
      - name: payment
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.payment.image.repo }}:{{ .Values.payment.image.tag }}
        command:
        - /app
        - -decline={{ .Values.payment.declinePaymentsOverAmount }}
        env:
        - name: SERVICE_NAME
          value: payment
        - name: SERVICE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: SIDECAR_INGEST_URL
          value: http://127.0.0.1:{{ .Values.poeSidecar.containerPort }}/prove
        {{- if .Values.zipkin.enabled }}
        - name: ZIPKIN
          value: http://{{ .Values.zipkin.url }}:9411/api/v1/spans
        {{- end }}
        resources:
{{ toYaml .Values.payment.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.payment.containerPort }}
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
{{- if lt (int .Values.payment.containerPort) 1024 }}
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
{{- end }}
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.payment.containerPort }}
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.payment.containerPort }}
          initialDelaySeconds: 180
          periodSeconds: 3
      {{- if .Values.poeSidecar.enabled }}
      - name: poe-sidecar
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.poeSidecar.image.repo }}:{{ .Values.poeSidecar.image.tag }}
        ports:
        - containerPort: {{ .Values.poeSidecar.containerPort }}
        env:
        - name: SERVICE_NAME
          value: payment
        - name: SERVICE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: LISTEN_ADDR
          value: 127.0.0.1:{{ .Values.poeSidecar.containerPort }}
        resources:
{{ toYaml .Values.poeSidecar.resources | indent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.poeSidecar.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.poeSidecar.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
      {{- end }}
