---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment
  template:
    metadata:
      labels:
        name: payment
      {{- if .Values.istio.enabled }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      {{- end }}
    spec:
      containers:
      - name: payment
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.payment.image.repo }}:{{ .Values.payment.image.tag }}
        command:
        - /app
        - -decline={{ .Values.payment.declinePaymentsOverAmount }}
        resources:
{{ toYaml .Values.payment.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.payment.containerPort }}
        {{- if .Values.zipkin.enabled }}
        env:
        - name: ZIPKIN
          value: http://{{ .Values.zipkin.url }}:9411/api/v1/spans
        {{- end }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
{{- if lt (int .Values.payment.containerPort) 1024 }}
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
{{- end }}
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.payment.containerPort }}
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.payment.containerPort }}
          initialDelaySeconds: 180
          periodSeconds: 3
      {{- if .Values.payment.sidecar.enabled }}
      - name: payment-sidecar
        image: {{if .Values.global.registry}}{{ .Values.global.registry }}/{{end}}{{ .Values.payment.sidecar.image }}:{{ .Values.payment.sidecar.tag }}
        command:
        - sh
        - -c
        - while true; do wget -qO- http://127.0.0.1:{{ .Values.payment.containerPort }}/health || true; sleep {{ .Values.payment.sidecar.intervalSeconds }}; done
        resources:
{{ toYaml .Values.payment.sidecar.resources | indent 10 }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          readOnlyRootFilesystem: true
      {{- end }}
