---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test-poe
  labels:
    name: load-test-poe
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: load-test
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
      - name: load-test
        # image: weaveworksdemos/load-test:0.1.1
        image: dev/load-test
        imagePullPolicy: Never
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              locust \
                --host http://front-end.sock-shop-poe.svc.cluster.local \
                -f /config/locustfile.py \
                --headless \
                -u 3 \
                -r 1 \
                --run-time 5m \
                --csv /results/loadtest;
              sleep 2m 
            done
        volumeMounts:
          - name: results
            mountPath: /results
      volumes:
        - name: results
          emptyDir: {}
      nodeSelector:
        beta.kubernetes.io/os: linux
