---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-test
  labels:
    name: load-test
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: load-test
  template:
    metadata:
      labels:
        name: load-test
    spec:
      containers:
      - name: load-test
        # image: weaveworksdemos/load-test:0.1.1
        image: dev/load-test
        imagePullPolicy: Never
        command: ["/bin/sh", "-c"]
        args:
          - |
            # while true; do
            locust \
              --host http://front-end.sock-shop.svc.cluster.local \
              -f /config/locustfile.py \
              --headless \
              -u 3 \
              -r 1 \
              --run-time 10m \
              --csv /results/loadtest;
            sleep 3m               
            # done
            
            locust \
              --host http://front-end.sock-shop.svc.cluster.local \
              -f /config/locustfile.py \
              --headless \
              -u 6 \
              -r 2 \
              --run-time 10m \
              --csv /results/loadtest;
            sleep 3m
            
            locust \
              --host http://front-end.sock-shop.svc.cluster.local \
              -f /config/locustfile.py \
              --headless \
              -u 10 \
              -r 4 \
              --run-time 10m \
              --csv /results/loadtest;
            sleep 3m

        volumeMounts:
          - name: results
            mountPath: /results
      volumes:
        - name: results
          emptyDir: {}
      nodeSelector:
        beta.kubernetes.io/os: linux
