---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: poe-circuit-artifacts-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/poe-circuit-artifacts"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poe-circuit-artifacts-pvc
  namespace: sock-shop-poe
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: poe-logs-pv
#   labels:
#     type: local
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/tmp/poe-logs"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: poe-logs-pvc
#   namespace: sock-shop-poe
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 2Gi


