---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  labels:
    name: orders
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: orders
  template:
    metadata:
      labels:
        name: orders
    spec:
      containers:
      - name: orders
        image: dev/orders
        imagePullPolicy: Never 
        env:
        - name: JAVA_OPTS
          value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dspring.zipkin.enabled=false
        - name: POE_SIDECAR_URL
          value: "http://localhost:8089/prove"
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 80
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      - name: orders-poe-sidecar
        image: dev/sidecar
        imagePullPolicy: Never
        env:
        - name: CIRCUIT_DIR
          valueFrom:
            configMapKeyRef:
              name: poe-sidecar-config
              key: circuit-dir
        - name: SERVICE_ID
          valueFrom:
            configMapKeyRef:
              name: poe-sidecar-config
              key: service-id-orders
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: poe-sidecar-config
              key: backend-url-orders
        - name: NODE_OPTIONS
          value: "--max-old-space-size=6144"
        ports:
        - containerPort: 8089
        resources:
          limits:
            cpu: 2000m
            memory: 6Gi
          requests:
            cpu: 1000m
            memory: 3Gi
        volumeMounts:
        - name: circuit-artifacts
          mountPath: /opt/circuit
        - name: logs-volume
          mountPath: /app/logs
        - name: tmp-volume
          mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        - name: circuit-artifacts
          persistentVolumeClaim:
            claimName: poe-circuit-artifacts-pvc
        - name: logs-volume
          persistentVolumeClaim:
            claimName: poe-logs-pvc
      nodeSelector:
        beta.kubernetes.io/os: linux
    
