---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    name: payment
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: payment
  template:
    metadata:
      labels:
        name: payment
    spec:
      containers:
      - name: payment
        image: dev/payment
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 99m
            memory: 100Mi
        ports:
        - containerPort: 80
        env:
        - name: SIDECAR_INGEST_URL
          value: "http://localhost:8089/prove"
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
      - name: payment-poe-sidecar
        image: dev/sidecar
        imagePullPolicy: Never
        env:
        - name: CIRCUIT_DIR
          valueFrom:
            configMapKeyRef:
              name: poe-sidecar-config
              key: circuit-dir
        - name: SERVICE_ID
          valueFrom:
            configMapKeyRef:
              name: poe-sidecar-config
              key: service-id-payment
        - name: BACKEND_URL
          valueFrom:
            configMapKeyRef:
              name: poe-sidecar-config
              key: backend-url-payment
        - name: NODE_OPTIONS
          value: "--max-old-space-size=6144"
        ports:
        - containerPort: 8089
        resources:
          limits:
            cpu: 2000m
            memory: 6Gi
          requests:
            cpu: 1000m
            memory: 3Gi
        volumeMounts:
        - name: circuit-artifacts
          mountPath: /opt/circuit
        - name: logs-volume
          mountPath: /app/logs
        - name: tmp-volume
          mountPath: /tmp
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 180
          periodSeconds: 3
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
        - name: circuit-artifacts
          persistentVolumeClaim:
            claimName: poe-circuit-artifacts-pvc
        - name: logs-volume
          persistentVolumeClaim:
            claimName: poe-logs-pvc
